### ISSUE TITLE
Perhaps support DualUse's API?

### ISSUE THREAD

**Issue by algernon** [gedankenlab/Kaleidoscope-Qukeys#12]
As `Qukeys` does what `DualUse` was meant to do, but in a much more reliable manner, I'd like to deprecate `DualUse` and recommend `Qukeys` instead. For this, it would be amazing if `Qukeys` would support the in-keymap markup `DualUse` does, in addition to what it already does. That markup is much more limited, but would allow people to easily migrate, and to express some of the use-cases within the keymap only.

Being able to express it on the keymap alone also means that it becomes a lot easier to support the plugin from within Chrysalis, and allow people to have Qukeys without recompiling their firmware.

If you aren't against this idea, I'll go ahead and prepare a pull request that adds `DualUse` API support.

**Comment by gedankenexperimenter** [comment]
I like the idea, as long as it doesn't add _too_ much complexity to the code. I had originally been planning to try to store the `Qukey` table in PROGMEM, since everything but the `state` bits could be static, but that would have meant a second array in RAM just for state (which could maybe be stored with just a single bit per key, if we're clever…), so I just put everything in RAM to make it work while keeping it simple.

So, the only idea that comes to mind for supporting `DualUse` declarations is to have a second `Qukey` array (or we could get away with just the state bits) dynamically allocated on startup by reading the keymap.

I'm looking forward to seeing what you come up with!

**Comment by gedankenexperimenter** [comment]
As a side note, even if `Qukeys` can replace `DualUse` entirely, I'm not sure it should; it's certainly much more code and memory heavy.

On another note, I don't really know how well Qukeys works with other plugins. It definitely wants its handler to run first (or at least before other plugins involved in the keyboard report), and probably needs to implement key masking to prevent bugs that are probably in there. Basically, it seems to work, but I don't have much faith in it yet. =)

**Comment by algernon** [comment]
Well, `DualUse` suffers from a bunch of issues `Qukeys` does not have, so even now, I think it is in a better shape. If it wants to be the first plugin, that's not an issue as far as the transition is concerned, in my opinion. :)

I'll go ahead and prep a PR in the next day or two, and we'll see how to proceed from there.

**Comment by gedankenexperimenter** [comment]
I don't know how much you've looked at the code yet, but I have rough idea of how we might do this. We could have `lookupQukey()` return a second special value (e.g. `QUKEY_DUAL_USE`), and have a third case in most of the places where there are just two now. The `state` member of the `Qukey` structure would need to be stored elsewhere, at least for these "extra" qukeys, so it would probably make sense to use a byte array as a bitfield to store state information. It would only need to be as big as the number of keys, and we could do it with just one bit per key by checking to see if the key is in the queue, and if it's pressed (but not toggled on) or toggled off to determine what the state bit means.

That might be premature optimization, but it neatly solves the problem of knowing at compile time how big to make the array for the state values.

**Comment by gedankenexperimenter** [comment]
I'm in the midst of writing code to store the qukey state in a bitfield now. You might want to wait until I finish that sometime later today before working on this.

**Comment by algernon** [comment]
My next longer stretch when I can do non-trivial keyboard work is likely Thursday, so \o/

(I don't mind rewriting/rebasing stuff, either, done that a lot with various Kaleidoscope plugins over the past year or so :))

**Comment by gedankenexperimenter** [comment]
Well, I just finished the bitfield state system; it was easier than I thought it would be. That should definitely simplify the changes you want to make.

On a related note, I'm still a bit shaky on how to correctly declare and initialize things so they get linked properly, and I'm not sure how to define the qukeys array so that it gets stored in PROGMEM (which is now possible). If you feel like throwing that in along with the DualUse API stuff, I wouldn't object.

**Comment by algernon** [comment]
Note taken. I'll probably throw that in separately, because that seems like a smaller change that I can squeeze in before Thursday.
