### ISSUE TITLE
Qukey on fn makes fn layer stick on

### ISSUE THREAD

**Issue by ryansch** [gedankenlab/Kaleidoscope-Qukeys#32]
I tried setting this up with `kaleidoscope::Qukey(0, 3, 6, Key_Escape)` but I don't get any escape presses and the fn button sticks on until I hit the one on the other half.

Running with https://github.com/keyboardio/Arduino-Boards/commit/f07a8e75cc19580d8776b1d9b2c338f0d74c9178 to get the changes needed as current master just breaks my keyboard.

**Comment by gedankenexperimenter** [comment]
You've almost certainly got the configuration backwards from the way you want it. In the keymap, you want to use the keycode for the "tap" function (i.e. `Key_Escape`), and in the qukey definition, you want:
```c++
kaleidoscope::Qukey(0, 3, 6, ShiftToLayer(FUNCTION))
```
It does sound like there's a bug here, though; I'll have to look into it.

**Comment by gedankenexperimenter** [comment]
Alternatively, you could just put the following in your keymap:
```
LT(FUNCTION, Escape)
```

**Comment by ryansch** [comment]
To be clear, I'm trying to get the fn key to emit escape when tapped for use with vim.  I'd still like it to work while held for layer shifting.

**Comment by ryansch** [comment]
Good call on `LT`.

**Comment by gedankenexperimenter** [comment]
Yes, I understand. I really ought to update the documentation to clarify that, as well.

**Comment by ryansch** [comment]
It works with LT.  Would the correct version of this in native qukeys be `kaleidoscope::Qukey(0, 2, 6, ShiftToLayer(FUNCTION))`?  I found https://github.com/keyboardio/Kaleidoscope-Hardware-Model01/blob/c126e1b27b58c007b9acf1d262154ddd0fc05b58/src/Kaleidoscope-Hardware-Model01.h#L209 as a reference.

**Comment by gedankenexperimenter** [comment]
I have confirmed that the bug where the keyboard gets stuck on a layer is because there's a new lookup of the `Key` from that layer, and the release is sent as that new keycode, not the layer shift key from the original keypress. I can fix this, but I'm not going to bother, because a layer shift as a primary keycode on a Qukey is completely nonsensical, and I'd rather have a very obvious bug to help users get their configuration right than to fix this Henny Youngman bug at the cost of added code and an ultimately less desirable – albeit more "correct" – behaviour.
